
[[eventos]]
youtube = "sl9djoCHV-0"
ativo = true
dia = "2022-09-30"
titulo = "Depressão Atípica"
assessor_slugs = ["eduardo-augusto-galindo-de-lima"]
cartaz = "img/bp-2022-09-30.png"
descricao = """
A depressão pode se "disfarçar" num sorriso. 
Na "depressão sorridente" a pessoa encobre 
inconscientemente seus sintomas para que os 
outros não percebam a dor e o sofrimento 
que ela enfrenta. Trata-se de uma 
"depressão atípica" muito difícil de se diagnosticar."""
online = true


[[eventos]]
youtube = "GOq6LKnLWkw"
ativo = true
dia = "2022-06-24"
titulo = "Estresse: um bem, um mal"
assessor_slugs = ["eduardo-augusto-galindo-de-lima"]
cartaz = "img/bp-2022-06-24.png"
descricao = """
Saiba mais sobre essa reação do organismo que pode ser boa ou má e amplie
o olhar e a percepção de si mesmo. Vamos falar também sobre formas critativas
para evitar o adoecimento."""
online = true

[[eventos]]
youtube = "-cRn9Cb9ZX8"
ativo = true
dia = "2022-05-27"
titulo = "Síndrome de Pânico"
assessor_slugs = ["eduardo-augusto-galindo-de-lima"]
cartaz = "img/bp-2022-05-27.png"
descricao = """
Vamos esclarecer dúvidas sobre essa doença que afeta milhares de pessoas em
todo o mundo."""
online = true

[[eventos]]
ativo = true
dia = "2022-02-25"
titulo = "Teologia e os LGBT+"
assessor_slugs = ["wellington-heleno-da-silva"]
cartaz = "img/bp-2022-02-25.png"
descricao = """
Longe de ser uma questão meramente abstrata, o tema da teologia e os LGBT+ se
lança a uma realidade que diz respeito à vida concreta de muitas pessoas que
nem sempre são acolhidas pela comunidade cristã."""
online = true

[[eventos.convidados]]
nome = "Pe. Luís Corrêa Lima"

[[eventos]]
youtube = "NlG1iCbRvOY"
ativo = true
dia = "2022-03-25"
titulo = "Massoterapia"
assessor_slugs = ["wojciech-mittelstaedt-adalberto"]
cartaz = "img/bp-2022-03-25.png"
descricao = """
A massoterapia nos ajuda a viver com mais qualidade tanto nos aspectos físicos
quanto mentais."""
online = true

[[eventos.convidados]]
nome = "Ir. Jyothi Joseph Satyanapalli, do PIME"

[[eventos]]
youtube = "0-QVm32Nb7M"
ativo = true
dia = "2022-04-08"
titulo = "Guerra na Ucrânia: Aspectos Psicológicos da Agressividade e do Autoritarismo"
assessor_slugs = ["wojciech-mittelstaedt-adalberto"]
cartaz = "img/bp-2022-04-08.png"
descricao = """
Os aspectos econômicos, culturais, sociais e morais de uma nação que podem ter
relação com os aspectos individuais da psique."""
online = true

[[eventos]]
dia = "2022-07-22"

[[eventos]]
dia = "2022-08-26"

[[eventos]]
dia = "2022-09-30"

[[eventos]]
dia = "2022-10-28"

[[eventos]]
dia = "2022-11-25"
