[[cursos]]
assessor_slugs = ["wellington-heleno-da-silva"]
dataiso = "2024-07-16"
titulo = "O Curador Ferido: Autoperdão e a Capacidade para Manter a Esperança"
descricao = """Neste curso, exploraremos a experiência do 'curador ferido', 
aqueles indivíduos que dedicam suas vidas a cuidar e curar os outros, mas que 
eventualmente se encontram em um estado de desilusão. Abordaremos os sinais e 
sintomas de esgotamento emocional e desgaste compassivo, destacando como esses 
fatores podem minar a capacidade de manter a esperança e examinaremos os impactos 
negativos da falta de esperança, que podem levar à depressão e à desilusão com a 
própria vida pessoal e vocacional. Abordaremos também a influência e relação do EU 
versus a Comunidade na construção de um espaço interno psicológico propício para 
cultivar a capacidade humana de sonhar, fantasiar, imaginar, brincar e, por fim, 
manter a esperança viva, mesmo em face de desafios e adversidades."""
cartaz = "img/curso-2024-07-16.png"
link_inscricao = "https://forms.gle/uD9aahi5rT8nFbTA6"
online = true
# Para o caso de horário e local personalizados utilize as seguintes variaveis:
# Detalhes no arquivo componentes/lista_de_cursos.pug
# Como a data para exibicao e criacao do link de agenda sao diferentes eh
# necessario manter hora e minuto em variaveis independentes
horaInicio = 19
minInicio = 30
horaFim = 21
minFim = 0
local = "Sede do Instituto Acolher - ITA"

[[cursos]]
assessor_slugs = ["ivan-rodrigues-e-silva-filho"]
dataiso = "2024-06-15"
titulo = "A Psicologia como instrumento adequado para formação humana na vida sacerdotal, religiosa e laical."
descricao = """O curso objetiva promover conhecimento sobre a importância do uso adequado, e assertivo, dos 
serviços psicológicos e da atuação do profissional da psicologia para a formação humana. A ideia é fornecer 
dados sobre o manuseio devido das ferramentas da psicoterapia e da avaliação psicológica, a partir das 
orientações da Igreja Católica, dos princípios éticos e científicos da psicologia e das reflexões de autores 
que lidam com o tema. Este trabalho tem como base teórica o conteúdo do meu livro lançado pelas Edições Loyola 
em 2023, 'A Psicologia na Vida Religiosa e Sacerdotal – por uma formação humana de qualidade', assim como obras 
de Jung, Viktor Frankl, Antoine Vergote, Stephen Finn. Edênio Valle, Anderson Frezzato, Ênio Brito, 
Mário Aletti e outros."""
cartaz = "img/curso-2024-06-15.png"
link_inscricao = "https://forms.gle/FropG3m54b3o627ZA"
online = true
# Para o caso de horário e local personalizados utilize as seguintes variaveis:
# Detalhes no arquivo componentes/lista_de_cursos.pug
# Como a data para exibicao e criacao do link de agenda sao diferentes eh
# necessario manter hora e minuto em variaveis independentes
horaInicio = 9
minInicio = 0
horaFim = 16
minFim = 0
local = "Sede do Instituto Acolher - ITA"

[[cursos]]
assessor_slugs = ["lourdes-degrandis"]
dataiso = "2024-05-18"
titulo = "Ecos da Vida - Experiências da vida que ecoam em seu cotidiano"
descricao = """O curso é destinado a todas as pessoas, sem restrições. O objetivo é proporcionar momentos de diálogo 
com você e o grupo sobre os ecos que as emoções e sentimentos tem no cotidiano da vida. 
Será uma oportunidade de experiênciar em você o que a vida lhe oferece e usufruir disso 
para sua saúde física, mental, emocional e espiritual!"""
cartaz = "img/curso-2024-05-18.png"
link_inscricao = "https://forms.gle/657otZKb2hUVURgeA"
online = true
# Para o caso de horário e local personalizados utilize as seguintes variaveis:
# Detalhes no arquivo componentes/lista_de_cursos.pug
# Como a data para exibicao e criacao do link de agenda sao diferentes eh
# necessario manter hora e minuto em variaveis independentes
horaInicio = 9
minInicio = 0
horaFim = 11
minFim = 0
local = "Sede do Instituto Acolher - ITA"

[[cursos]]
assessor_slugs = ["vagner-sanagiotto"]
dataiso = "2024-04-08"
titulo = "O psicodiagnóstico da experiência religiosa problemática no contexto clínico"
descricao = """O curso é destinado a psicólogos que trabalham nos seminários e casas religiosas, 
formadores/as responsáveis pela formação à vida religiosa consagrada e presbiteral, 
animadores vocacionais, superiores/as."""
cartaz = "img/curso-2024-04-08.png"
link_inscricao = "https://forms.gle/cm6GtHAiFjQjPW9u5"
online = true
# Para o caso de horário e local personalizados utilize as seguintes variaveis:
# Detalhes no arquivo componentes/lista_de_cursos.pug
# Como a data para exibicao e criacao do link de agenda sao diferentes eh
# necessario manter hora e minuto em variaveis independentes
horaInicio = 19
minInicio = 30
horaFim = 21
minFim = 0
local = "Sede do Instituto Acolher - ITA"
